module.exports = {
  apps: [{
    name: 'verticals',
    script: './src/index.js',
    exec_mode: 'cluster',
    instances: 1,
    // instances: 'max',
    node_args: '-r dotenv/config',
    env: {
      // NODE_ENV: 'development',
      // HOST: '0.0.0.0',
      // PORT: 3000,
      // JWT_EXPIRE: '1Y',
      // JWT_SECRET: 'verticals_secret_yB4wh92erhF',
      // CORS_ORIGIN: '*',
      // METRICS_ENABLED: true,
      // METRICS_PORT: 3001,
      // METRICS_HOST: '0.0.0.0',
      // METRICS_ROUTE: '/metrics',
      // METRICS_TIMEOUT: 5000,
      // SWAGGER_JSON_ROUTE: '/doc.json',
      // SWAGGER_TITLE: 'Verticals Backend',
      // SWAGGER_VERSION: '0.1.0',
      // SWAGGER_DESCRIPTION: 'Backend part for verticals project',
      // SWAGGER_HOST: '0.0.0.0:3000',
      // SWAGGER_BASE_PATH: '/api',
      // LOG_FILE_NAME: `app_${new Date().getTime()}`,
      // CDN_LINK: 'cdn.verticals.xom9ik.com',
      // MAX_SOCKET_CONNECTIONS: 10,
      // UPLOADS_FOLDER: 'uploads',
      // COMMENTS_FOLDER: 'comments',
    },
    env_development: {
      watch: ['./src'],
      args: [
        '--color',
      ],
    },
    env_production: {
      NODE_ENV: 'production',
    },
  }],
};
