module.exports = {
  tables: {
    tokens: 'tokens',
    users: 'users',
    boards: 'boards',
    boardsAccess: 'boards_access',
    columns: 'columns',
    headings: 'headings',
    todos: 'todos',
    subTodos: 'sub_todos',
    comments: 'comments',
    commentFiles: 'comment_files',
    boardPositions: 'board_positions',
    columnPositions: 'column_positions',
    headingPositions: 'heading_positions',
    todoPositions: 'todo_positions',
    subTodoPositions: 'sub_todo_positions',
    commentLikes: 'comment_likes',
  },
};
